# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{amee-data-persistence}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Hetherington", "Andrew Berkeley", "James Smith", "George Palmer"]
  s.date = %q{2011-07-15}
  s.description = %q{Part of the AMEE AppKit this gem provides storage and retrival of data provided by the Data Abstraction gem}
  s.email = %q{help@amee.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "README",
    "Rakefile",
    "VERSION",
    "amee-data-persistence.tmproj",
    "init.rb",
    "lib/amee-data-persistence.rb",
    "lib/amee/data_abstraction/calculation_collection.rb",
    "lib/amee/data_abstraction/persistence_support.rb",
    "lib/amee/db/calculation.rb",
    "lib/amee/db/config.rb",
    "lib/amee/db/term.rb",
    "lib/generators/persistence/persistence_generator.rb",
    "lib/generators/persistence/templates/config/persistence.yml.erb",
    "lib/generators/persistence/templates/db/migrate/001_create_persistence_tables.rb",
    "lib/generators/persistence/templates/db/migrate/002_add_unit_columns.rb",
    "lib/generators/persistence/templates/db/migrate/003_add_value_types.rb",
    "rails/init.rb",
    "spec/amee/db/calculation_spec.rb",
    "spec/amee/db/config_spec.rb",
    "spec/amee/db/persistence_support_spec.rb",
    "spec/amee/db/term_spec.rb",
    "spec/database.yml",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/AMEE/amee-data-persistence}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Persistent storage of calculations performed against the AMEE API}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<amee-data-abstraction>, [">= 1.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec_spinner>, ["= 1.1.3"])
      s.add_development_dependency(%q<flexmock>, ["> 0.8.6"])
      s.add_development_dependency(%q<activerecord>, ["~> 2.3.5"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
    else
      s.add_dependency(%q<amee-data-abstraction>, [">= 1.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec_spinner>, ["= 1.1.3"])
      s.add_dependency(%q<flexmock>, ["> 0.8.6"])
      s.add_dependency(%q<activerecord>, ["~> 2.3.5"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
    end
  else
    s.add_dependency(%q<amee-data-abstraction>, [">= 1.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rspec>, ["= 1.3.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec_spinner>, ["= 1.1.3"])
    s.add_dependency(%q<flexmock>, ["> 0.8.6"])
    s.add_dependency(%q<activerecord>, ["~> 2.3.5"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
  end
end

